version: '3.8'

services:
  oracle:
    platform: linux/amd64
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle
    hostname: oracle
    restart: always
    ports:
      - 1521:1521
    environment:
      ORACLE_SID: XE
      ORACLE_PWD: oracle
      ORACLE_USERNAME: system
      ORACLE_ALLOW_REMOTE: true