spring:
  profiles:
    include:
      - payment

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: venepiano
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.venepiano.domain
  type-handlers-package: com.venepiano.core.handler
  configuration:
    map-underscore-to-camel-case: true