-- 회원 테이블
CREATE TABLE MEMBER
(
    MBR_ID          VARCHAR(20) PRIMARY KEY,
    CUST_CO_CD      VARCHAR(10) NOT NULL,
    NAME            VARCHAR(100),
    EMAIL           VARCHAR(100),
    PHONE           VARCHAR(20),
    BIRTH_DATE      DATE,
    GENDER          CHAR(1),
    JOIN_DATE       DATE      DEFAULT CURRENT_DATE,
    STATUS          CHAR(1)   DEFAULT 'A',
    LAST_LOGIN_DATE TIMESTAMP,
    TEAM_ID         VARCHAR(10),
    DEPT_ID         VARCHAR(10),
    DIV_ID          VARCHAR(10),
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 팀 테이블
CREATE TABLE TEAM
(
    TEAM_ID      VARCHAR(10) PRIMARY KEY,
    TEAM_NAME    VARCHAR(100) NOT NULL,
    DEPT_ID      VARCHAR(10),
    MANAGER_ID   VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 부서 테이블
CREATE TABLE DEPARTMENT
(
    DEPT_ID      VARCHAR(10) PRIMARY KEY,
    DEPT_NAME    VARCHAR(100) NOT NULL,
    DIV_ID       VARCHAR(10),
    MANAGER_ID   VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 본부 테이블
CREATE TABLE DIVISION
(
    DIV_ID       VARCHAR(10) PRIMARY KEY,
    DIV_NAME     VARCHAR(100) NOT NULL,
    MANAGER_ID   VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 외주업체(벤더사) 테이블
CREATE TABLE VENDOR
(
    VENDOR_ID           VARCHAR(10) PRIMARY KEY,
    VENDOR_NAME         VARCHAR(100) NOT NULL,
    BUSINESS_NO         VARCHAR(20),
    CONTACT_PERSON      VARCHAR(100),
    CONTACT_EMAIL       VARCHAR(100),
    CONTACT_PHONE       VARCHAR(20),
    ADDRESS             VARCHAR(200),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE   DATE,
    STATUS              CHAR(1)   DEFAULT 'A',
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 프로젝트 테이블
CREATE TABLE PROJECT
(
    PROJECT_ID   VARCHAR(10) PRIMARY KEY,
    PROJECT_NAME VARCHAR(100) NOT NULL,
    TEAM_ID      VARCHAR(10)  NOT NULL,
    VENDOR_ID    VARCHAR(10),
    START_DATE   DATE,
    END_DATE     DATE,
    BUDGET       NUMERIC(15, 2),
    STATUS       VARCHAR(10) DEFAULT 'ACTIVE',
    DESCRIPTION  TEXT,
    PM_MBR_ID    VARCHAR(20),
    CREATED_DATE TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- 상품 카테고리 테이블
CREATE TABLE PRODUCT_CATEGORY
(
    CATEGORY_ID        VARCHAR(10) PRIMARY KEY,
    CATEGORY_NAME      VARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID VARCHAR(10),
    CREATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 상품 테이블
CREATE TABLE PRODUCT
(
    PRODUCT_ID     VARCHAR(20) PRIMARY KEY,
    PRODUCT_NAME   VARCHAR(200)   NOT NULL,
    CATEGORY_ID    VARCHAR(10),
    PRICE          NUMERIC(15, 2) NOT NULL,
    DISCOUNT_RATE  NUMERIC(5, 2) DEFAULT 0,
    STOCK_QUANTITY NUMERIC(10)   DEFAULT 0,
    DESCRIPTION    TEXT,
    STATUS         CHAR(1)       DEFAULT 'A',
    PROJECT_ID     VARCHAR(10),
    CREATED_DATE   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- 주문 마스터 테이블
CREATE TABLE ORDER_MASTER
(
    ORDER_ID         VARCHAR(20) PRIMARY KEY,
    MBR_ID           VARCHAR(20)    NOT NULL,
    ORDER_DATE       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT     NUMERIC(15, 2) NOT NULL,
    DISCOUNT_AMOUNT  NUMERIC(15, 2) DEFAULT 0,
    SHIPPING_FEE     NUMERIC(10, 2) DEFAULT 0,
    FINAL_AMOUNT     NUMERIC(15, 2) NOT NULL,
    STATUS           VARCHAR(10)    DEFAULT 'PENDING',
    SHIPPING_ADDRESS VARCHAR(200),
    SHIPPING_CONTACT VARCHAR(20),
    DELIVERY_REQUEST TEXT,
    CREATED_DATE     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- 주문 상세 테이블
CREATE TABLE ORDER_DETAIL
(
    ORDER_DETAIL_ID VARCHAR(20) PRIMARY KEY,
    ORDER_ID        VARCHAR(20)    NOT NULL,
    PRODUCT_ID      VARCHAR(20)    NOT NULL,
    QUANTITY        NUMERIC(10)    NOT NULL,
    UNIT_PRICE      NUMERIC(15, 2) NOT NULL,
    DISCOUNT_AMOUNT NUMERIC(15, 2) DEFAULT 0,
    LINE_AMOUNT     NUMERIC(15, 2) NOT NULL,
    CREATED_DATE    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);


-- 결제 수단 테이블
CREATE TABLE PAYMENT_MEAN (
                              MEAN_ID VARCHAR(10) PRIMARY KEY,
                              MEAN_NAME VARCHAR(50) NOT NULL,
                              DESCRIPTION VARCHAR(200),
                              CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 결제 수단 상세 테이블
CREATE TABLE PAYMENT_MEAN_DTL (
                                  MEAN_DTL_ID VARCHAR(10) PRIMARY KEY,
                                  MEAN_ID VARCHAR(10) NOT NULL,
                                  DTL_NAME VARCHAR(50) NOT NULL,
                                  DESCRIPTION VARCHAR(200),
                                  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 결제 마스터 테이블
CREATE TABLE PAYMENT (
                         PAYMENT_ID VARCHAR(20) PRIMARY KEY,
                         ORDER_ID VARCHAR(20) NOT NULL,
                         PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         PAYMENT_AMOUNT NUMERIC(15,2) NOT NULL,
                         STTL_NO VARCHAR(30) NOT NULL,
                         MEAN_DTL_ID VARCHAR(10) NOT NULL,
                         STATUS VARCHAR(10) DEFAULT 'COMPLETED',
                         CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 현금 결제 테이블
CREATE TABLE PAYMENT_CASH (
                              STTL_NO VARCHAR(30) PRIMARY KEY,
                              PAYMENT_ID VARCHAR(20) NOT NULL,
                              BANK_CODE VARCHAR(10),
                              ACCOUNT_NO VARCHAR(30),
                              ACCOUNT_HOLDER VARCHAR(100),
                              CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 카드 결제 테이블
CREATE TABLE PAYMENT_CARD (
                              STTL_NO VARCHAR(30) PRIMARY KEY,
                              PAYMENT_ID VARCHAR(20) NOT NULL,
                              CARD_TYPE VARCHAR(20),
                              CARD_NO VARCHAR(16),
                              CARD_HOLDER VARCHAR(100),
                              APPROVAL_NO VARCHAR(30),
                              INSTALLMENT_MONTHS NUMERIC(2) DEFAULT 0,
                              CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 쿠폰 결제 테이블
CREATE TABLE PAYMENT_COUPON (
                                STTL_NO VARCHAR(30) PRIMARY KEY,
                                PAYMENT_ID VARCHAR(20) NOT NULL,
                                COUPON_CODE VARCHAR(30),
                                COUPON_TYPE VARCHAR(20),
                                DISCOUNT_AMOUNT NUMERIC(15,2),
                                CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 포인트 마스터 테이블
CREATE TABLE POINT_MASTER (
                              POINT_ID VARCHAR(20) PRIMARY KEY,
                              MBR_ID VARCHAR(20) NOT NULL,
                              POINT_TYPE VARCHAR(10) NOT NULL,
                              POINT_AMOUNT NUMERIC(10) NOT NULL,
                              PAYMENT_ID VARCHAR(20),
                              EXPIRE_DATE DATE,
                              STATUS CHAR(1) DEFAULT 'A',
                              DESCRIPTION VARCHAR(200),
                              CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 회사별 포인트 배정년도 테이블
CREATE TABLE COMPANY_POINT_ALLOCATION (
                                          ALLOCATION_ID VARCHAR(20) PRIMARY KEY,
                                          CUST_CO_CD VARCHAR(10) NOT NULL,
                                          ASSN_YR NUMERIC(4) NOT NULL,
                                          TOTAL_POINT NUMERIC(15) NOT NULL,
                                          REMAINING_POINT NUMERIC(15) NOT NULL,
                                          START_DATE DATE,
                                          END_DATE DATE,
                                          STATUS CHAR(1) DEFAULT 'A',
                                          CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 회원별 포인트 배정 테이블
CREATE TABLE MEMBER_POINT_ALLOCATION (
                                         MBR_POINT_ID VARCHAR(20) PRIMARY KEY,
                                         ALLOCATION_ID VARCHAR(20) NOT NULL,
                                         MBR_ID VARCHAR(20) NOT NULL,
                                         ALLOCATED_POINT NUMERIC(10) NOT NULL,
                                         USED_POINT NUMERIC(10) DEFAULT 0,
                                         REMAINING_POINT NUMERIC(10),
                                         CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 포인트 사용 이력 테이블
CREATE TABLE POINT_USAGE_HISTORY (
                                     USAGE_ID VARCHAR(20) PRIMARY KEY,
                                     MBR_POINT_ID VARCHAR(20) NOT NULL,
                                     PAYMENT_ID VARCHAR(20),
                                     USAGE_AMOUNT NUMERIC(10) NOT NULL,
                                     USAGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     DESCRIPTION VARCHAR(200),
                                     CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 환불 테이블
CREATE TABLE REFUND (
                        REFUND_ID VARCHAR(20) PRIMARY KEY,
                        PAYMENT_ID VARCHAR(20) NOT NULL,
                        REFUND_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        REFUND_AMOUNT NUMERIC(15,2) NOT NULL,
                        REFUND_REASON TEXT,
                        STATUS VARCHAR(10) DEFAULT 'PENDING',
                        CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IDX_MEMBER_TEAM ON MEMBER(TEAM_ID);
CREATE INDEX IDX_MEMBER_DEPT ON MEMBER(DEPT_ID);
CREATE INDEX IDX_MEMBER_DIV ON MEMBER(DIV_ID);
CREATE INDEX IDX_MEMBER_CUSTCO ON MEMBER(CUST_CO_CD);
CREATE INDEX IDX_TEAM_DEPT ON TEAM(DEPT_ID);
CREATE INDEX IDX_DEPT_DIV ON DEPARTMENT(DIV_ID);
CREATE INDEX IDX_PROJECT_TEAM ON PROJECT(TEAM_ID);
CREATE INDEX IDX_PRODUCT_CATEGORY ON PRODUCT(CATEGORY_ID);
CREATE INDEX IDX_PRODUCT_PROJECT ON PRODUCT(PROJECT_ID);
CREATE INDEX IDX_ORDER_MEMBER ON ORDER_MASTER(MBR_ID);
CREATE INDEX IDX_ORDER_DETAIL_ORDER ON ORDER_DETAIL(ORDER_ID);
CREATE INDEX IDX_ORDER_DETAIL_PRODUCT ON ORDER_DETAIL(PRODUCT_ID);
CREATE INDEX IDX_PAYMENT_ORDER ON PAYMENT(ORDER_ID);
CREATE INDEX IDX_PAYMENT_STTL_NO ON PAYMENT(STTL_NO);
CREATE INDEX IDX_PAYMENT_MEAN_DTL ON PAYMENT(MEAN_DTL_ID);
CREATE INDEX IDX_POINT_MEMBER ON POINT_MASTER(MBR_ID);
CREATE INDEX IDX_POINT_PAYMENT ON POINT_MASTER(PAYMENT_ID);
CREATE INDEX IDX_COMPANY_POINT_CUSTCO ON COMPANY_POINT_ALLOCATION(CUST_CO_CD, ASSN_YR);
CREATE INDEX IDX_MEMBER_POINT_MBR ON MEMBER_POINT_ALLOCATION(MBR_ID);
CREATE INDEX IDX_POINT_USAGE_MBR_POINT ON POINT_USAGE_HISTORY(MBR_POINT_ID);
CREATE INDEX IDX_REFUND_PAYMENT ON REFUND(PAYMENT_ID);


commit;


-- 2. 실적 기여도 테이블 생성 (테스트 데이터 용)
CREATE TABLE PROJECT_CONTRIBUTION (
                                      PROJECT_ID VARCHAR(10),
                                      MBR_ID VARCHAR(20),
                                      CONTRIBUTION_RATE NUMERIC(5,2),
                                      ROLE VARCHAR(50),
                                      PRIMARY KEY (PROJECT_ID, MBR_ID)
);


-- 1. 멘토-멘티 매핑 테이블 생성 (테스트 데이터 용)
CREATE TABLE MEMBER_MENTOR (
                               MENTEE_ID VARCHAR(20),
                               MENTOR_ID VARCHAR(20),
                               START_DATE DATE,
                               END_DATE DATE,
                               STATUS CHAR(1) DEFAULT 'A',
                               PRIMARY KEY (MENTEE_ID, MENTOR_ID)
);